package com.example.weatherforecast.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_primary = Color(0xFF4ED8E9)
val md_theme_onPrimary = Color(0xFF00363C)
val md_theme_primaryContainer = Color(0xFF004F57)
val md_theme_onPrimaryContainer = Color(0xFF90F1FF)
val md_theme_secondary = Color(0xFFB1CBCF)
val md_theme_onSecondary = Color(0xFF1C3438)
val md_theme_secondaryContainer = Color(0xFF324B4E)
val md_theme_onSecondaryContainer = Color(0xFFCDE7EB)
val md_theme_tertiary = Color(0xFF54D7F2)
val md_theme_onTertiary = Color(0xFF003640)
val md_theme_tertiaryContainer = Color(0xFF004E5B)
val md_theme_onTertiaryContainer = Color(0xFFA9EDFF)
val md_theme_error = Color(0xFFFFB4AB)
val md_theme_errorContainer = Color(0xFF93000A)
val md_theme_onError = Color(0xFF690005)
val md_theme_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_background = Color(0xFF001F25)
val md_theme_onBackground = Color(0xFFA6EEFF)
val md_theme_surface = Color(0xFF001F25)
val md_theme_onSurface = Color(0xFFA6EEFF)
val md_theme_surfaceVariant = Color(0xFF3F484A)
val md_theme_onSurfaceVariant = Color(0xFFBEC8CA)
val md_theme_outline = Color(0xFF899294)
val md_theme_inverseOnSurface = Color(0xFF001F25)
val md_theme_inverseSurface = Color(0xFFA6EEFF)
val md_theme_inversePrimary = Color(0xFF006973)
val md_theme_surfaceTint = Color(0xFF4ED8E9)
val md_theme_outlineVariant = Color(0xFF3F484A)
val md_theme_scrim = Color(0xFF000000)


